// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsUMU-cbRzBUuFnBuHWq2-YsRTo6fl6d0',
    appId: '1:33715196859:web:dd463c446e8b9f87ef6a9e',
    messagingSenderId: '33715196859',
    projectId: 'alvek001',
    authDomain: 'alvek001.firebaseapp.com',
    storageBucket: 'alvek001.appspot.com',
    measurementId: 'G-PXPD2V8CRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1BEytNK_vBm1qra5SUGGyBy8tDmbV9g',
    appId: '1:33715196859:android:18c064a3477760d5ef6a9e',
    messagingSenderId: '33715196859',
    projectId: 'alvek001',
    storageBucket: 'alvek001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvLZwREYC5VmHdsjEl_Dz6_7_V6_ObMlI',
    appId: '1:33715196859:ios:22daf7fffb17937bef6a9e',
    messagingSenderId: '33715196859',
    projectId: 'alvek001',
    storageBucket: 'alvek001.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvLZwREYC5VmHdsjEl_Dz6_7_V6_ObMlI',
    appId: '1:33715196859:ios:22daf7fffb17937bef6a9e',
    messagingSenderId: '33715196859',
    projectId: 'alvek001',
    storageBucket: 'alvek001.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsUMU-cbRzBUuFnBuHWq2-YsRTo6fl6d0',
    appId: '1:33715196859:web:68d8189239a2cdabef6a9e',
    messagingSenderId: '33715196859',
    projectId: 'alvek001',
    authDomain: 'alvek001.firebaseapp.com',
    storageBucket: 'alvek001.appspot.com',
    measurementId: 'G-3LJ4CQKGS2',
  );

}